### ISSUE TITLE
Ledger device turns off making it impossible to sign certain transactions

### ISSUE THREAD

**Issue by 314159265359879** [Zondax/ledger-stacks#171] opened 2024-09-12 20:44 UTC
See here https://github.com/leather-io/extension/issues/5857

Ledger Nano S+ firmware 1.1.2 and stacks app 0.24.2 (I checked with two devices same model).

:link: [zboto Link](https://app.clickup.com/t/8695tbppu)

**Comment by 314159265359879** [comment] 2024-09-12 20:47
Reproduction steps
Connect Ledger to Leather (Stacks)
Click swap in the wallet
Choose a token pair and any amount
Click review and swap
Click Swap
See error: in leather shows loading animation with "Waiting for your approval"
Ledger device turns off, or screen goes blank which makes it look turned off.

**Comment by Darrenpeaker** [comment] 2024-09-12 21:10
> Reproduction steps Connect Ledger to Leather (Stacks) Click swap in the wallet Choose a token pair and any amount Click review and swap Click Swap See error: in leather shows loading animation with "Waiting for your approval" Ledger device turns off, or screen goes blank which makes it look turned off.

@314159265359879 seems like you're encountering an issue with your Ledger device when trying to swap tokens using Leather (Stacks). It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledger Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by 314159265359879** [comment] 2024-09-13 07:18
Retested with Xverse, the issue is the same there, screen turns off. 
used app.bitflow.finance/trade to initiate a transaction to sign on the device.

**Comment by Darrenpeaker** [comment] 2024-09-13 10:41
> Retested with Xverse, the issue is the same there, screen turns off. used app.bitflow.finance/trade to initiate a transaction to sign on the device.

@314159265359879 are you able to get it solve with the support team ?

**Comment by brandonmarshall-tm** [comment] 2024-09-17 02:28
Received a user report that attempting this multiple times caused their Ledger to reset completely, with them needing to re-enter their seed phrase. It happened multiple times after multiple attempts.

**Comment by TeddyManZ** [comment] 2024-10-01 06:15
Withdraw LP on Alex have the same issue and Alex LP tokens can't send to another wallet, so my fund have been stuck because of this bug.

**Comment by 314159265359879** [comment] 2024-10-01 07:26
> Withdraw LP on Alex have the same issue and Alex LP tokens can't send to another wallet, so my fund have been stuck because of this bug.

Thanks for sharing, I am checking with the Zondax team for an update on this issue and its resolution. We are aware this is a serious blocker. 

This is not an issue with [0.23.3](https://github.com/Zondax/ledger-stacks/releases/tag/v0.23.3) of the Stacks app, perhaps Zondax has a step by step guide on how to revert to an older version of the app to allow transactions in case of a dire need.

**Comment by TeddyManZ** [comment] 2024-10-01 18:43
> > Withdraw LP on Alex have the same issue and Alex LP tokens can't send to another wallet, so my fund have been stuck because of this bug.
> 
> Thanks for sharing, I am checking with the Zondax team for an update on this issue and its resolution. We are aware this is a serious blocker.
> 
> This is not an issue with [0.23.3](https://github.com/Zondax/ledger-stacks/releases/tag/v0.23.3) of the Stacks app, perhaps Zondax has a step by step guide on how to revert to an older version of the app to allow transactions in case of a dire need.

Is the sideload the app only work on Ledger Nano S and Nano S plus ?
I only have Nano X.

**Comment by 314159265359879** [comment] 2024-10-03 07:35
> > > Withdraw LP on Alex have the same issue and Alex LP tokens can't send to another wallet, so my fund have been stuck because of this bug.
> > 
> > 
> > Thanks for sharing, I am checking with the Zondax team for an update on this issue and its resolution. We are aware this is a serious blocker.
> > This is not an issue with [0.23.3](https://github.com/Zondax/ledger-stacks/releases/tag/v0.23.3) of the Stacks app, perhaps Zondax has a step by step guide on how to revert to an older version of the app to allow transactions in case of a dire need.
> 
> Is the sideload the app only work on Ledger Nano S and Nano S plus ? I only have Nano X.

Hi again, sideloading doesn't work on the Nano X, because that device doesn't allow sideloading by design. In addition, I tested side loading 0.23.3 and that wasn't supported via hub.zondax.ch/stacks when I tried a couple days ago (with nano S+), I have asked someone from Zondax to see what is causing the issue, I have not yet heard back. I will share here when I do have a viable workaround.

**Comment by ainhoa-a** [comment] 2024-10-04 07:09
You should be able now to install through Ledger Live the previous version on your NanoX while this issue is being investigated 
<img width="400" alt="image" src="https://github.com/user-attachments/assets/3bfd618f-b56b-4a7e-bf47-d58549739aea">

**Comment by rzucher** [comment] 2024-10-07 14:54
Hey guys, I'm not a developer but an web3 user and ether.fi moderator :)
I'm here to share my experience in the previous 3 days, where I've tried to use Bitflow's pool (stx-ststx) and at the moment of signing the transaction, my Ledger Nano X would bug, do not show the approval part and reset completely to fabric conditions (3 times) in the same scenario. Once, when trying to figure if the problem was in Ledger/Stacks app or Leather/Xverse, I've taken the device out and he went to booting mode for 3 full days on the plug. 
Anyways, I see people are aware of the bug and hope to be fixed soon. Thanks!

**Comment by ainhoa-a** [comment] 2024-10-07 15:25
Hi @rzucher we have rolled back to previous version while we keep investigating this issue. You should be able to instal 23.3 again from Ledger Live. Sorry for the inconveniences.

**Comment by neithanmo** [comment] 2024-10-10 06:38
Hi @rzucher @314159265359879 
I am investigating this issue, so it happens after transaction is reviewed and upon approval(where the transaction signing comes in) it crashes?

**Comment by rzucher** [comment] 2024-10-10 12:08
Hello Natanael, actually my problem went a little bit further my device
actually reseted to fabric conditions three times. it would bug when the
transaction should be appearing, and then it would turn off and back to
fabric. Once it even went to a booting screen where it took 3 days on the
plug to come back working normally


*Rodrigo M. Zucher*

**Comment by rzucher** [comment] 2024-10-10 13:19
1- No, the transaction (entering stx-ststx pool on Bitflow) never actually goes to the device screen, it only appears as generating/generated on Xverser/leather (tried both) 
2- crashes few seconds after requesting the transaction 
 
 If you want, drop me your email I can share my logs if you think is useful :)

**Comment by neithanmo** [comment] 2024-10-10 14:20
Can you share those logs here? so everyone can be aware of the data we are looking at. and we can share here parts of it while going through

**Comment by rzucher** [comment] 2024-10-10 15:48
yep sure, I was double guessing if its ok to share it, anyways here u go: 
[Uploading Logs RMZ.json…]()

**Comment by 314159265359879** [comment] 2024-10-11 00:12
@neithanmo 
> In case helpful in debugging, here's a Leather build that logs the tx before it's passed to the device https://github.com/leather-io/extension/pull/5885

**Comment by neithanmo** [comment] 2024-10-11 06:37
> yep sure, I was double guessing if its ok to share it, anyways here u go: Uploading Logs RMZ.json…


it seems the link is pointing to this issue, no logs file

**Comment by neithanmo** [comment] 2024-10-11 07:09
> @neithanmo
> 
> > In case helpful in debugging, here's a Leather build that logs the tx before it's passed to the device [leather-io/extension#5885](https://github.com/leather-io/extension/pull/5885)


it seems the dev run(to run in testnet with some funds) does not allow doing swaps which I believe is the transaction type that triggers this issue sometimes

**Comment by neithanmo** [comment] 2024-10-23 05:53
We could reproduce the issue and got the testing data we needed. fix on the making via #173

**Comment by neithanmo** [comment] 2024-10-23 06:44
I could signed a swap transaction:

https://explorer.hiro.so/txid/0xb3e88ea9f8319d6bab31a598c5b9c0f3de7ba3cc9d6720b09a0dfbccdbc26d82?chain=mainnet

so will close this issue via #173

**Closed by neithanmo** 2024-10-23 06:44 UTC

**Comment by rzucher** [comment] 2024-10-29 20:02
@neithanmo hey guys, bringing that up , now on Ledger Flex 😭 , it's not going back to fabric conditions, it just doesn't load transactions. but it was indeed working before Nakamoto... idk

**Comment by 314159265359879** [comment] 2024-10-29 20:40
@rzucher what is the version number of the Stacks App and firmware shown in Ledger Live?

**Comment by rzucher** [comment] 2024-10-29 20:44
@314159265359879 24.2

**Comment by neithanmo** [comment] 2024-10-30 12:01
@rzucher what is your firmware version? maybe you should update it in ledger live

**Comment by rzucher** [comment] 2024-10-30 12:44
@neithanmo OS 1.1.1 , no update available on my side

**Comment by neithanmo** [comment] 2024-11-04 08:17
I is difficult to tell, the fix was in the UI section, way before transaction is loaded and parsed
the fix was using a rust library that does not use core::fmt implementation for integer to string conversions, we actually have a test from the blob I got here, and runs just fine on flex device.
Let me check again, but it could be dev mode or something, flex is new and we are still adding support for in other ledger applications we have built

**Comment by rzucher** [comment] 2024-11-12 17:54
Just got my device reseted for the 4th time, I've also raised this matter on support channel of stacks community. It happened specifically when trying to use Bitflow's swap aggregator. Isn't it possible to return the app to previous version like you guys did with nano x? (using ledger flex)
